"use client";
import React from 'react';
import { motion } from 'framer-motion';
import {
  BriefcaseBusiness,
  ClipboardCheck,
  BarChart4,
  MessageSquareText
} from 'lucide-react';

const features = [
  {
    title: 'AI-Powered Mock Interviews',
    description: 'Simulate real interviews with role-specific questions generated by AI.',
    icon: <BriefcaseBusiness size={32} />,
  },
  {
    title: 'Instant AI Feedback',
    description: 'Receive actionable feedback and improvement suggestions after every mock.',
    icon: <ClipboardCheck size={32} />,
  },
  {
    title: 'Performance Analytics',
    description: 'Track your growth with detailed performance reports and improvement charts.',
    icon: <BarChart4 size={32} />,
  },
  {
    title: 'Personalized Coaching Tips',
    description: 'Get tailored advice and strategies from AI to enhance your communication and confidence.',
    icon: <MessageSquareText size={32} />,
  },
];

const container = {
  hidden: {},
  show: {
    transition: {
      staggerChildren: 0.3,  // slightly increased delay between items
    },
  },
};

const cardVariant = {
  hidden: { opacity: 0, y: 30 },
  show: { opacity: 1, y: 0, transition: { duration: 0.6 } }, // smoother, slower
};

const FeatureSection = () => {
  return (
    <div className="bg-[#0F172A] text-white py-16 px-4 md:px-12 ">
      <h2 className="text-2xl md:text-3xl font-bold text-center mb-12">
        Powerful Features to Ace Your Interviews
      </h2>
      <motion.div
        variants={container}
        initial="hidden"
        whileInView="show"
        viewport={{ once: false, amount: 0.3 }} // triggers every time user scrolls in
        className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 max-w-6xl mx-auto"
      >
        {features.map((feature, index) => (
          <motion.div
            key={index}
            variants={cardVariant}
            className="border border-white/10 bg-[#1E293B] rounded-xl p-6 hover:shadow-xl hover:border-white/20 transition"
          >
            <div className="mb-4 text-primary flex items-center justify-center">{feature.icon}</div>
            <h3 className="text-lg font-semibold mb-2 flex items-center text-center">{feature.title}</h3>
            <p className="text-sm text-white/70 text-center">{feature.description}</p>
          </motion.div>
        ))}
      </motion.div>
    </div>
  );
};

export default FeatureSection;
